version:  '2'
services:
  web:
    build: .
    entrypoint: ['pserve']
    command : [ "kbm.ini", "--reload"]
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "6543:6543"
    environment:
      DATABASE_URL: postgresql://kbm@postgres/kbm
  postgres:
     image: postgres:9.6.2-alpine
     environment:
         POSTGRES_USER: kbm
         POSTGRES_DB: kbm
