version:  '3'
services:
  web:
    build: .
    entrypoint: ['pserve']
    command : [ "kbm.ini", "--reload"]
#    command : >
#              sh -c "python initialize_db.py
#                          && pserve kbm.ini --reload"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "6542:6542"
    environment:
      DATABASE_URL: postgresql://kbm@postgres/kbm
  postgres:
     image: postgres:9.6.2-alpine
     environment:
         POSTGRES_USER: kbm
         POSTGRES_DB: kbm
